export const LOGIN_USER = 'LOGIN_USER';
export const SET_USER = 'SET_USER';
export const USER_FAILED = 'USER_FAILED';
export const POFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_FAILED = 'PROFILE_FAILED';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';

export const PLACARDS_LOADING = 'PLACARDS_LOADING';
export const PLACARDS_FAILED = 'PLACARDS_FAILED';
export const UPDATE_PLACARDS = 'UPDATE_PLACARDS';

export const PLACARD_LOADING = 'PLACARD_LOADING';
export const PLACARD_FAILED = 'PLACARD_FAILED';
export const UPDATE_PLACARD = 'UPDATE_PLACARD';
export const DELETE_PLACARD = 'DELETE_PLACARD';

export const AUTHOR_LOADING = 'AUTHOR_LOADING';
export const UPDATE_AUTHOR = 'UPDATE_AUTHOR';
export const AUTHOR_FAILED = 'AUTHOR_FAILED';